### ISSUE TITLE
LOAD segment with RWX permissions

### ISSUE THREAD

**Issue by nmenon** [siemens/k3-rti-wdt#2]
/opt/cross-gcc-linux-12/bin/../lib/gcc/arm-none-linux-gnueabihf/12.2.1/../../../../arm-none-linux-gnueabihf/bin/ld: warning: k3-rti-wdt.fw has a LOAD segment with RWX permissions
arm-none-linux-gnueabihf-gcc (Arm GNU Toolchain 12.2.Rel1 (Build arm-12.24)) 12.2.1 20221205

**Comment by jan-kiszka** [comment]
This seems to help, but I'm not yet sure I understand everything:
```
diff --git a/Makefile b/Makefile
index 51b6eb0..178ca4b 100644
--- a/Makefile
+++ b/Makefile
@@ -11,7 +11,7 @@ CC = gcc
 RTI_MODULE = 1
 
 CFLAGS = -mcpu=cortex-r5 -DRTI_MODULE=$(RTI_MODULE)
-LDFLAGS = -nostdlib -N -Wl,-strip-all -Wl,--build-id -static
+LDFLAGS = -nostdlib -N -Wl,-strip-all -Wl,--build-id -static -Wl,--nmagic
 
 k3-rti-wdt.fw: lscript.lds firmware.o
 	$(CROSS_COMPILE)$(CC) -o $@ -T $^ $(LDFLAGS)
```
